public  class Calculation {
    public integer add(integer a, integer b){
        integer sum1 = a + b;
        return sum1;
    }
    public integer subtract(integer a, integer b){
        integer sum2 =a - b;
        return sum2;
    }
    public integer multiply(integer a, integer b){
        integer sum3 =a * b;
        return sum3;
    }
    public integer divide(integer a, integer b){
        integer sum4 =a / b;
        return sum4;
    }
}
