public class CaseTriggerHandler {
    
    public static integer countTriggerExecution = 0 ;
    public static integer countTriggerRecords = 0;
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /*public static void insertCase() {
        case nc= new case();
        nc.Subject = 'Case Tigger Test';
        nc.Status='New';
        nc.Origin='Web';
        insert nc;
    }
    public static void updateCase() {
     Case cs = [Select subject from case ORDER BY CreatedDate DESC limit 1];
     cs.Subject= 'Case Tigger Test Update';
     update cs;
    }
    public static void deleteCase() {
        Case deletecs = [Select id from case ORDER BY CreatedDate DESC limit 1];
        delete deletecs;
    }
    */
}
